Page({
    data:{
        legends:[
            {
                name:'小乔',
                title:'法师',
                src:'./img/小乔.jpg'
            },
            {
                name:'虞姬',
                title:'射手',
                src:'./img/虞姬.jpg'
            },
            {
                name:'花木兰',
                title:'战士/刺客',
                src:'./img/木兰.jpg'
            },
            {
                name:'大乔',
                title:'坦克/辅助',
                src:'./img/大乔.jpg'
            },
            {
                name:'露娜',
                title:'法师/战士',
                src:'./img/露娜.jpg'
            }
        ]
    }
})